api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *


urlpatterns = [
    url(r'^ion_channel/create/$', login_required(IonChannelCreateAPI.as_view()), name="ion-channel-create-api"),
    url(r'^ion_channel/list/$', IonChannelListAPI.as_view(), name="ion-channel-list-api"),
    url(r'^ion_channel/details/(?P<pk>[0-9]+)/$', IonChannelDetailsAPI.as_view(), name="ion-channel-details-api"),

    url(r'^reference/create/$', login_required(ReferenceCreateAPI.as_view()), name="reference-create-api"),
    url(r'^reference/list/$', ReferenceListAPI.as_view(), name="reference-list-api"),
    url(r'^reference/details/(?P<pk>[0-9]+)/$', ReferenceDetailsAPI.as_view(), name="reference-details-api"),

    url(r'^cell/create/$', login_required(CellCreateAPI.as_view()), name="cell-create-api"),
    url(r'^cell/list/$', CellListAPI.as_view(), name="cell-list-api"),
    url(r'^cell/details/(?P<pk>[0-9]+)/$', CellDetailsAPI.as_view(), name="cell-details-api"),

    url(r'^patch_clamp/create/$', login_required(PatchClampCreateAPI.as_view()), name="patch-clamp-create-api"),
    url(r'^patch_clamp/list/$', PatchClampListAPI.as_view(), name="patch-clamp-list-api"),
    url(r'^patch_clamp/details/(?P<pk>[0-9]+)/$', PatchClampDetailsAPI.as_view(), name="patch-clamp-details-api"),

    url(r'^graph/create/$', login_required(GraphCreateAPI.as_view()), name="graph-create-api"),
    url(r'^graph/list/$', GraphListAPI.as_view(), name="graph-list-api"),
    url(r'^graph/details/(?P<pk>[0-9]+)/$', GraphDetailsAPI.as_view(), name="graph-details-api"),

    url(r'^graph_data/create/$', login_required(GraphDataCreateAPI.as_view()), name="graph-data-create-api"),
    url(r'^graph_data/list/$', GraphDataListAPI.as_view(), name="graph-data-list-api"),
    url(r'^graph_data/details/(?P<pk>[0-9]+)/$', GraphDataDetailsAPI.as_view(), name="graph-data-details-api"),

    url(r'^user/list/$', UserListAPI.as_view(), name="user-list-api"),
    url(r'^user/details/(?P<pk>[0-9]+)/$', UserDetailsAPI.as_view(), name="user-details-api"),

]

urlpatterns = format_suffix_patterns(urlpatterns)

digitizer/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^cvs_export/$', csv_export, name='csv_export'),
    url(r'^(?P<graph_id>[0-9]+)$', digitize, name='digitize'),
]

ion_channel/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .form import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^home$', IonChannelList.as_view(), name='home'),

    url(r'^ion_channels/(?P<ionChannelId>[0-9]+)*$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^ion_channels/dashboard$', ionchannel_dashboard, name='ion-channel-dashboard'),
    url(r'^ion_channels/detail/(?P<pk>[0-9]+)$', IonChannelDetail.as_view(), name='ion-channel-detail'),
    url(r'^ion_channels/create/(?P<ionChannelId>[0-9]+)*$', login_required(IonChannelCreate.as_view()), name='ion-channel-create'),
    url(r'^ion_channels/update/(?P<pk>[0-9]+)$', login_required(IonChannelUpdate.as_view()), name='ion-channel-update'),
    url(r'^ion_channels/delete/(?P<pk>[0-9]+)$', login_required(IonChannelDelete.as_view()), name='ion-channel-delete'),

    url(r'^reference/create/(?P<ionChannelId>[0-9]+)*$', login_required(ReferenceCreate.as_view()), name='reference-create'),
    url(r'^reference/(?P<ionChannelId>[0-9]+)*$', ReferenceList.as_view(), name='reference-index'),
    url(r'^reference/update/(?P<pk>[0-9]+)$', login_required(ReferenceUpdate.as_view()), name='reference-update'),
    url(r'^reference/delete/(?P<pk>[0-9]+)$', login_required(ReferenceDelete.as_view()), name='reference-delete'),
    url(r'^reference/auto_create/$', login_required(ReferenceWizard.as_view([PubForm, ReferenceForm])), name='reference-auto-create'),

    url(r'^cell/create/$', login_required(CellCreate.as_view()), name='cell-create'),

    url(r'^ion_channel_model/(?P<ionChannelId>[0-9]+)*$', IonChannelModelList.as_view(), name='ion-channel-model-index'),
    url(r'^ion_channel_model/create$', login_required(IonChannelModelCreate.as_view()), name='ion-channel-model-create'),
    url(r'^ion_channel_model/update/(?P<pk>[0-9]+)$', login_required(IonChannelModelUpdate.as_view()), name='ion-channel-model-update'),
    url(r'^ion_channel_model/delete/(?P<pk>[0-9]+)$', login_required(IonChannelModelDelete.as_view()), name='ion-channel-model-delete'),

    url(r'^patch_clamp/(?P<ionChannelId>[0-9]+)*$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create/(?P<ionChannelId>[0-9]+)*$', login_required(PatchClampCreate.as_view()), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', login_required(PatchClampUpdate.as_view()), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', login_required(PatchClampDelete.as_view()), name='patch-clamp-delete'),
    url(r'^patch_clamp/detail/(?P<pk>[0-9]+)$', PatchClampDetail.as_view(), name='patch-clamp-detail'),

    url(r'^graph/(?P<ionChannelId>[0-9]+)*$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create/(?P<ionChannelId>[0-9]+)*$', login_required(GraphCreate.as_view()), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', login_required(GraphUpdate.as_view()), name='graph-update'),
    url(r'^graph/plot/(?P<pk>[0-9]+)$', login_required(save_digitized_plot), name='graph-plot'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', login_required(GraphDelete.as_view()), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', login_required(save_graph_data), name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataDelete.as_view()), name='graph-data-delete'),
    url(r'^graph_data/update/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataUpdate.as_view()), name='graph-data-update'),

]

web_app/urls.py
"""
chopen URL Configuration
"""
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
import sys
# from ion_channel.views import index
from .views import index

# TODO: Check for conflicts in two accounts url pattern
# login_required() from 'django.contrib.auth.urls' redirects to accounts/login/ by default!

urlpatterns = [
    # url(r'^cms/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^pages/', include(wagtail_urls)),
    # url(r'^accounts/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include(('account.urls', 'account'), namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^digitizer/', include(('digitizer.urls', 'digitizer'), namespace="digitizer"), ),
    url(r'^ion_channel/', include(('ion_channel.urls', 'ion_channel'), namespace="ion_channel"), ),
    url(r'^api/', include(('api.urls', 'api'), namespace="api"), ),
    url(r'^index$', index ),
    url(r'^$', index ,name='home'),
    # url(r'^$', include(('homepage.urls', 'homepage'), namespace='homepage')),
    # url(r'^explorer/', include('explorer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitizer/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from ion_channel.models import Graph


def index(request):
    return render(request, 'digitizer/index.html')


def digitize(request, graph_id):
    graph = get_object_or_404(Graph, pk=graph_id)
    return render(request, 'digitizer/index.html', {'graph': graph})


def csv_export(request):
    data = request.POST.get("data")
    file_name = request.POST.get("filename")
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="' + file_name + '.csv"'

    response.write(json.loads(data))
    return response

digitizer/templates/digitizer/index.html
{% extends "base_collapsed_sidebar.html" %}

{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans 'Digitizer' %}{% endblock %}
{% block page_header %}{% trans 'Digitizer' %}{% endblock %}
{% block page_header_description %}{% trans 'Digitizing graphs' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'ion_channel:graph-index' %}"><i class="fa fa-bar-chart"></i> {% trans 'Graph' %}</a></li>
    <li class="active">{% trans 'Digitizer' %}</li>
{% endblock %}

{% block inline-css %}
    <link rel="stylesheet" href="{% static 'digitizer/thirdparty/toastr/toastr.min.css' %}" type="text/css"
          media="screen"/>
    <link rel="stylesheet" href="{% static 'digitizer/css/cwd-style.css' %}" type="text/css" media="screen"/>
{% endblock %}

{% block inline-script %}
    {% include 'digitizer/includes/_scripts.html' %}
    <script src="{% static 'digitizer/js/cwd.js' %}"></script>
    <script src="{% static 'digitizer/thirdparty/numeric-1.2.6.min.js' %}"></script>
    <script src="{% static 'digitizer/thirdparty/toastr/toastr.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="loadingCurtain" style="display:none">Loading application, please wait...</div>
    <form id="frm_graph_data" method="post" class="form" action="{% url 'ion_channel:graph-data-create' %}">
        {% csrf_token %}
        <input type="hidden" id="graph_url" name="graph_url" value="/media/{{ graph.file }}"/>
        <input type="hidden" id="graph_id" name="graph_id" value="{{ graph.id }}"/>
        <input type="hidden" id="series_name" name="series_name"/>
        <input type="hidden" id="series_data" name="series_data"/>
    </form>

    <div class="row" id="allContainer">
        {% include 'digitizer/includes/_toolbox.html' %}
        <div id="mainContainer" class="col-sm-9">
            <div id="graphicsContainer" class="box box-primary">

                {% include 'digitizer/includes/_toolbars.html' %}
                <div class="box-body">
                    <div id="canvasDiv" style="position:relative;" class="box-body">
                        <canvas id="mainCanvas" class="canvasLayers" style="z-index:1;" width=600 height=400></canvas>
                        <canvas id="dataCanvas" class="canvasLayers" style="z-index:2;" width=600 height=400></canvas>
                        <canvas id="drawCanvas" class="canvasLayers" style="z-index:3;" width=600 height=400></canvas>
                        <canvas id="hoverCanvas" class="canvasLayers" style="z-index:4;" width=600 height=400></canvas>
                        <canvas id="topCanvas" class="canvasLayers" style="z-index:5;" width=600 height=400></canvas>
                    </div>
                </div>
                <div class="overlay cwd-loading">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- popup windows go here -->
    {% include 'digitizer/includes/_dialogs.html' %}
{% endblock %}