account/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^edit/$', AccountEditView.as_view(), name='account-edit'),
]

api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *


urlpatterns = [
    url(r'^ion_channel/create/$', login_required(IonChannelCreateAPI.as_view()), name="ion-channel-create-api"),
    url(r'^ion_channel/list/$', IonChannelListAPI.as_view(), name="ion-channel-list-api"),
    url(r'^ion_channel/details/(?P<pk>[0-9]+)/$', IonChannelDetailsAPI.as_view(), name="ion-channel-details-api"),

    url(r'^reference/create/$', login_required(ReferenceCreateAPI.as_view()), name="reference-create-api"),
    url(r'^reference/list/$', ReferenceListAPI.as_view(), name="reference-list-api"),
    url(r'^reference/details/(?P<pk>[0-9]+)/$', ReferenceDetailsAPI.as_view(), name="reference-details-api"),

    url(r'^cell/create/$', login_required(CellCreateAPI.as_view()), name="cell-create-api"),
    url(r'^cell/list/$', CellListAPI.as_view(), name="cell-list-api"),
    url(r'^cell/details/(?P<pk>[0-9]+)/$', CellDetailsAPI.as_view(), name="cell-details-api"),

    url(r'^patch_clamp/create/$', login_required(PatchClampCreateAPI.as_view()), name="patch-clamp-create-api"),
    url(r'^patch_clamp/list/$', PatchClampListAPI.as_view(), name="patch-clamp-list-api"),
    url(r'^patch_clamp/details/(?P<pk>[0-9]+)/$', PatchClampDetailsAPI.as_view(), name="patch-clamp-details-api"),

    url(r'^graph/create/$', login_required(GraphCreateAPI.as_view()), name="graph-create-api"),
    url(r'^graph/list/$', GraphListAPI.as_view(), name="graph-list-api"),
    url(r'^graph/details/(?P<pk>[0-9]+)/$', GraphDetailsAPI.as_view(), name="graph-details-api"),

    url(r'^graph_data/create/$', login_required(GraphDataCreateAPI.as_view()), name="graph-data-create-api"),
    url(r'^graph_data/list/$', GraphDataListAPI.as_view(), name="graph-data-list-api"),
    url(r'^graph_data/details/(?P<pk>[0-9]+)/$', GraphDataDetailsAPI.as_view(), name="graph-data-details-api"),

    url(r'^user/list/$', UserListAPI.as_view(), name="user-list-api"),
    url(r'^user/details/(?P<pk>[0-9]+)/$', UserDetailsAPI.as_view(), name="user-details-api"),

]

urlpatterns = format_suffix_patterns(urlpatterns)

ion_channel/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .form import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^home$', IonChannelList.as_view(), name='home'),

    url(r'^ion_channels/(?P<ionChannelId>[0-9]+)*$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^ion_channels/dashboard$', ionchannel_dashboard, name='ion-channel-dashboard'),
    url(r'^ion_channels/detail/(?P<pk>[0-9]+)$', IonChannelDetail.as_view(), name='ion-channel-detail'),
    url(r'^ion_channels/create/(?P<ionChannelId>[0-9]+)*$', login_required(IonChannelCreate.as_view()), name='ion-channel-create'),
    url(r'^ion_channels/update/(?P<pk>[0-9]+)$', login_required(IonChannelUpdate.as_view()), name='ion-channel-update'),
    url(r'^ion_channels/delete/(?P<pk>[0-9]+)$', login_required(IonChannelDelete.as_view()), name='ion-channel-delete'),

    url(r'^reference/create/(?P<ionChannelId>[0-9]+)*$', login_required(ReferenceCreate.as_view()), name='reference-create'),
    url(r'^reference/(?P<ionChannelId>[0-9]+)*$', ReferenceList.as_view(), name='reference-index'),
    url(r'^reference/update/(?P<pk>[0-9]+)$', login_required(ReferenceUpdate.as_view()), name='reference-update'),
    url(r'^reference/delete/(?P<pk>[0-9]+)$', login_required(ReferenceDelete.as_view()), name='reference-delete'),
    url(r'^reference/auto_create/$', login_required(ReferenceWizard.as_view([PubForm, ReferenceForm])), name='reference-auto-create'),

    url(r'^cell/create/$', login_required(CellCreate.as_view()), name='cell-create'),

    url(r'^ion_channel_model/(?P<ionChannelId>[0-9]+)*$', IonChannelModelList.as_view(), name='ion-channel-model-index'),
    url(r'^ion_channel_model/create$', login_required(IonChannelModelCreate.as_view()), name='ion-channel-model-create'),
    url(r'^ion_channel_model/update/(?P<pk>[0-9]+)$', login_required(IonChannelModelUpdate.as_view()), name='ion-channel-model-update'),
    url(r'^ion_channel_model/delete/(?P<pk>[0-9]+)$', login_required(IonChannelModelDelete.as_view()), name='ion-channel-model-delete'),

    url(r'^patch_clamp/(?P<ionChannelId>[0-9]+)*$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create/(?P<ionChannelId>[0-9]+)*$', login_required(PatchClampCreate.as_view()), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', login_required(PatchClampUpdate.as_view()), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', login_required(PatchClampDelete.as_view()), name='patch-clamp-delete'),
    url(r'^patch_clamp/detail/(?P<pk>[0-9]+)$', PatchClampDetail.as_view(), name='patch-clamp-detail'),

    url(r'^graph/(?P<ionChannelId>[0-9]+)*$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create/(?P<ionChannelId>[0-9]+)*$', login_required(GraphCreate.as_view()), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', login_required(GraphUpdate.as_view()), name='graph-update'),
    url(r'^graph/plot/(?P<pk>[0-9]+)$', login_required(save_digitized_plot), name='graph-plot'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', login_required(GraphDelete.as_view()), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', login_required(save_graph_data), name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataDelete.as_view()), name='graph-data-delete'),
    url(r'^graph_data/update/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataUpdate.as_view()), name='graph-data-update'),

]

web_app/urls.py
"""
chopen URL Configuration
"""
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
import sys
# from ion_channel.views import index
from .views import index

# TODO: Check for conflicts in two accounts url pattern
# login_required() from 'django.contrib.auth.urls' redirects to accounts/login/ by default!

urlpatterns = [
    # url(r'^cms/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^pages/', include(wagtail_urls)),
    # url(r'^accounts/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include(('account.urls', 'account'), namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^digitizer/', include(('digitizer.urls', 'digitizer'), namespace="digitizer"), ),
    url(r'^ion_channel/', include(('ion_channel.urls', 'ion_channel'), namespace="ion_channel"), ),
    url(r'^api/', include(('api.urls', 'api'), namespace="api"), ),
    url(r'^index$', index ),
    url(r'^$', index ,name='home'),
    # url(r'^$', include(('homepage.urls', 'homepage'), namespace='homepage')),
    # url(r'^explorer/', include('explorer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/views.py
from django.http import JsonResponse
from django.views.generic import ListView
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')



class AjaxResponseMixin(object):
    """
    Mixin allows you to define alternative methods for ajax requests. Similar
    to the normal get, post, and put methods, you can use get_ajax, post_ajax,
    and put_ajax.
    """

    def dispatch(self, request, *args, **kwargs):
        request_method = request.method.lower()

        if request.is_ajax() and request_method in self.http_method_names:
            handler = getattr(self, u"{0}_ajax".format(request_method),
                              self.http_method_not_allowed)

            self.request = request
            self.args = args
            self.kwargs = kwargs
            return handler(request, *args, **kwargs)

        return super(AjaxResponseMixin, self).dispatch(
            request, *args, **kwargs)

    def get_ajax(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def post_ajax(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def put_ajax(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def delete_ajax(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class AjaxMixinListView(AjaxResponseMixin, ListView):
    def get_ajax(self, request, *args, **kwargs):
        self.template_name_suffix = '_list_ajax'
        return self.get(request, *args, **kwargs)


class BaseAjaxAction(AjaxResponseMixin):
    parentId_url_kwarg = None
    json_success_response = {'status': 'success', 'result': 'Entity data has been saved.'}
    json_error_response = {'status': 'error', 'message': 'Entity has not been saved.', 'validation': None}

    def get_ajax(self, request, *args, **kwargs):
        response = self.get(request, *args, **kwargs)
        if self.parentId_url_kwarg:
            response.context_data[self.parentId_url_kwarg] = kwargs[self.parentId_url_kwarg]

        return response

    def create_success_ajax_response(self):
        self.json_success_response['pk'] = self.object.pk
        return self.json_success_response

    def post_ajax(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            self.form_valid(form)
            response_data = self.create_success_ajax_response()
            return JsonResponse(response_data)
        else:
            self.json_error_response['validation'] = form.errors
            return JsonResponse(self.json_error_response, status=400)


class AjaxMixinCreateView(BaseAjaxAction):
    parentId_url_kwarg = None
    json_success_response = {'status': 'success', 'result': 'Entity has been saved.'}

    def get_ajax(self, request, *args, **kwargs):
        self.template_name_suffix = '_create_form_ajax'
        return super(AjaxMixinCreateView, self).get_ajax(self, request, *args, **kwargs)


class AjaxMixinUpdateView(BaseAjaxAction):
    parentId_url_kwarg = None
    json_success_response = {'status': 'success', 'result': 'Entity has been saved.'}

    def get_ajax(self, request, *args, **kwargs):
        self.template_name_suffix = '_update_form_ajax'
        return super(AjaxMixinUpdateView, self).get_ajax(self, request, *args, **kwargs)

    def post_ajax(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(AjaxMixinUpdateView, self).post_ajax(request, *args, **kwargs)


class AjaxMixinDeleteView(BaseAjaxAction):
    json_success_response = {'status': 'success', 'result': 'Entity has been deleted.'}

    def get_ajax(self, request, *args, **kwargs):
        self.template_name_suffix = '_confirm_delete_ajax'
        return super(AjaxMixinDeleteView, self).get_ajax(self, request, *args, **kwargs)

    def delete_ajax(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return JsonResponse(self.create_success_ajax_response())

    def post_ajax(self, request, *args, **kwargs):
        return self.delete_ajax(self, request, *args, **kwargs)

    def create_success_ajax_response(self):
        return self.json_success_response

web_app/templates/include/_main_header.html
{% load staticfiles %}
{% load i18n %}
<header class="main-header">
    <!-- Logo -->
    <a href="/index" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><strong>PDC</strong></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><strong>Chopen</strong></span>
    </a>

    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/index" class="navbar-brand"><b>Chopen</b></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'ion_channel:ion-channel-index' %}">
                    <i class='fa fa-neuter'></i><span>{% trans 'Ion Channels' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:patch-clamp-index' %}">
                    <i class='fa fa-pinterest-p'></i><span>{% trans 'Patch Clamps' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:graph-index' %}">
                    <i class='fa fa-bar-chart'></i><span>{% trans 'Figures' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:ion-channel-model-index' %}">
                    <i class='fa fa-area-chart'></i><span>{% trans 'Ion Channel Models' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:reference-index' %}">
                    <i class='fa fa-file-text-o'></i><span>{% trans 'References' %}</span></a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{% static 'third_party/lte/dist/img/avatar2.png' %}" class="user-image"
                             alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">
                            {% if user.first_name  %}
                                {{ user.first_name }} {{ user.last_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{% static 'third_party/lte/dist/img/avatar2.png' %}" class="img-circle"
                                 alt="User Image"/>
                            <p>
                                {% if user.first_name %}
                                    {{ user.first_name }} {{ user.last_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                                <small>{{ user.email }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{% url 'account:account-edit' %}" class="btn btn-default btn-flat">
                                    <i class="fa  fa-edit"></i><span> Edit Account</span>
                                </a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'password_change' %}" class="btn btn-default btn-flat">
                                    <i class="fa  fa-key"></i><span> Change Pass</span>
                                </a>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div>
                                <a href="{% url 'logout' %}" class="btn btn-default btn-flat center-block">
                                    <i class='fa fa-sign-out'></i><span> {% trans 'Sign out' %}</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
                {% else %}
                <div class="pull-right">
                    <a href="{% url 'login' %}" class="navbar-brand" role="button">
                        <i class='fa fa-sign-in'></i><span> {% trans 'Login' %}</span>
                    </a>
                    <a href="{% url 'account:register' %}" class="navbar-brand" role="button">
                        <i class='fa fa-user-plus'></i><span> {% trans 'Register' %}</span>
                    </a>
                </div>
                {% endif %}
            </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
</header>

web_app/templates/include/_main_sidebar.html
{% load staticfiles %}
{% load i18n %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <!--<div class="user-panel">-->
            <!--<div class="pull-left image">-->
                <!--<img src="{% static 'third_party/lte/dist/img/avatar5.png' %}" class="img-circle"-->
                     <!--alt="User Image"/>-->
            <!--</div>-->
            <!--<div class="pull-left info">-->
                <!--<p>Sample User</p>-->
                <!--&lt;!&ndash; Status &ndash;&gt;-->
                <!--<a href="#"><i class="fa fa-circle text-success"></i> Online</a>-->
            <!--</div>-->
        <!--</div>-->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <!-- Optionally, you can add icons to the links -->
            <li><a href="{% url 'home' %}">
                <i class='fa fa-neuter'></i><span>{% trans 'Ion Channels' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:patch-clamp-index' %}">
                <i class='fa fa-pinterest-p'></i><span>{% trans 'Patch Clamps' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:graph-index' %}">
                <i class='fa fa-bar-chart'></i><span>{% trans 'Figures' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:ion-channel-model-index' %}">
                <i class='fa fa-area-chart'></i><span>{% trans 'Ion Channel Models' %}</span></a>
            </li>
            <li><a href="{% url 'ion_channel:reference-index' %}">
                <i class='fa fa-file-text-o'></i><span>{% trans 'References' %}</span></a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

web_app/templates/include/_menu_header.html
{% load staticfiles %}
{% load i18n %}
<header class="main-header">
    <!-- Logo -->
    <a href="/index" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><strong>Chopen</strong></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><strong>Chopen</strong></span>
    </a>

    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/index" class="navbar-brand"><b>Chopen</b></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'ion_channel:ion-channel-index' %}">
                    <i class='fa fa-neuter'></i><span>{% trans 'Ion Channels' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:patch-clamp-index' %}">
                    <i class='fa fa-pinterest-p'></i><span>{% trans 'Patch Clamps' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:graph-index' %}">
                    <i class='fa fa-bar-chart'></i><span>{% trans 'Figures' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:ion-channel-model-index' %}">
                    <i class='fa fa-area-chart'></i><span>{% trans 'Ion Channel Models' %}</span></a>
                </li>
                <li><a href="{% url 'ion_channel:reference-index' %}">
                    <i class='fa fa-file-text-o'></i><span>{% trans 'References' %}</span></a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{% static 'third_party/lte/dist/img/avatar2.png' %}" class="user-image"
                             alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">
                            {% if user.first_name  %}
                                {{ user.first_name }} {{ user.last_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{% static 'third_party/lte/dist/img/avatar2.png' %}" class="img-circle"
                                 alt="User Image"/>
                            <p>
                                {% if user.first_name %}
                                    {{ user.first_name }} {{ user.last_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                                <small>{{ user.email }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{% url 'account:account-edit' %}" class="btn btn-default btn-flat">
                                    <i class="fa  fa-edit"></i><span> Edit Account</span>
                                </a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'password_change' %}" class="btn btn-default btn-flat">
                                    <i class="fa  fa-key"></i><span> Change Pass</span>
                                </a>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div>
                                <a href="{% url 'logout' %}" class="btn btn-default btn-flat center-block">
                                    <i class='fa fa-sign-out'></i><span> {% trans 'Sign out' %}</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
                {% else %}
                <div class="pull-right">
                    <a href="{% url 'login' %}" class="navbar-brand" role="button">
                        <i class='fa fa-sign-in'></i><span> {% trans 'Login' %}</span>
                    </a>
                    <a href="{% url 'account:register' %}" class="navbar-brand" role="button">
                        <i class='fa fa-user-plus'></i><span> {% trans 'Register' %}</span>
                    </a>
                </div>
                {% endif %}
            </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
</header>