api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *


urlpatterns = [
    url(r'^ion_channel/create/$', login_required(IonChannelCreateAPI.as_view()), name="ion-channel-create-api"),
    url(r'^ion_channel/list/$', IonChannelListAPI.as_view(), name="ion-channel-list-api"),
    url(r'^ion_channel/details/(?P<pk>[0-9]+)/$', IonChannelDetailsAPI.as_view(), name="ion-channel-details-api"),

    url(r'^reference/create/$', login_required(ReferenceCreateAPI.as_view()), name="reference-create-api"),
    url(r'^reference/list/$', ReferenceListAPI.as_view(), name="reference-list-api"),
    url(r'^reference/details/(?P<pk>[0-9]+)/$', ReferenceDetailsAPI.as_view(), name="reference-details-api"),

    url(r'^cell/create/$', login_required(CellCreateAPI.as_view()), name="cell-create-api"),
    url(r'^cell/list/$', CellListAPI.as_view(), name="cell-list-api"),
    url(r'^cell/details/(?P<pk>[0-9]+)/$', CellDetailsAPI.as_view(), name="cell-details-api"),

    url(r'^patch_clamp/create/$', login_required(PatchClampCreateAPI.as_view()), name="patch-clamp-create-api"),
    url(r'^patch_clamp/list/$', PatchClampListAPI.as_view(), name="patch-clamp-list-api"),
    url(r'^patch_clamp/details/(?P<pk>[0-9]+)/$', PatchClampDetailsAPI.as_view(), name="patch-clamp-details-api"),

    url(r'^graph/create/$', login_required(GraphCreateAPI.as_view()), name="graph-create-api"),
    url(r'^graph/list/$', GraphListAPI.as_view(), name="graph-list-api"),
    url(r'^graph/details/(?P<pk>[0-9]+)/$', GraphDetailsAPI.as_view(), name="graph-details-api"),

    url(r'^graph_data/create/$', login_required(GraphDataCreateAPI.as_view()), name="graph-data-create-api"),
    url(r'^graph_data/list/$', GraphDataListAPI.as_view(), name="graph-data-list-api"),
    url(r'^graph_data/details/(?P<pk>[0-9]+)/$', GraphDataDetailsAPI.as_view(), name="graph-data-details-api"),

    url(r'^user/list/$', UserListAPI.as_view(), name="user-list-api"),
    url(r'^user/details/(?P<pk>[0-9]+)/$', UserDetailsAPI.as_view(), name="user-details-api"),

]

urlpatterns = format_suffix_patterns(urlpatterns)

digitizer/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^cvs_export/$', csv_export, name='csv_export'),
    url(r'^(?P<graph_id>[0-9]+)$', digitize, name='digitize'),
]

ion_channel/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .form import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^home$', IonChannelList.as_view(), name='home'),

    url(r'^ion_channels/(?P<ionChannelId>[0-9]+)*$', IonChannelList.as_view(), name='ion-channel-index'),
    url(r'^ion_channels/dashboard$', ionchannel_dashboard, name='ion-channel-dashboard'),
    url(r'^ion_channels/detail/(?P<pk>[0-9]+)$', IonChannelDetail.as_view(), name='ion-channel-detail'),
    url(r'^ion_channels/create/(?P<ionChannelId>[0-9]+)*$', login_required(IonChannelCreate.as_view()), name='ion-channel-create'),
    url(r'^ion_channels/update/(?P<pk>[0-9]+)$', login_required(IonChannelUpdate.as_view()), name='ion-channel-update'),
    url(r'^ion_channels/delete/(?P<pk>[0-9]+)$', login_required(IonChannelDelete.as_view()), name='ion-channel-delete'),

    url(r'^reference/create/(?P<ionChannelId>[0-9]+)*$', login_required(ReferenceCreate.as_view()), name='reference-create'),
    url(r'^reference/(?P<ionChannelId>[0-9]+)*$', ReferenceList.as_view(), name='reference-index'),
    url(r'^reference/update/(?P<pk>[0-9]+)$', login_required(ReferenceUpdate.as_view()), name='reference-update'),
    url(r'^reference/delete/(?P<pk>[0-9]+)$', login_required(ReferenceDelete.as_view()), name='reference-delete'),
    url(r'^reference/auto_create/$', login_required(ReferenceWizard.as_view([PubForm, ReferenceForm])), name='reference-auto-create'),

    url(r'^cell/create/$', login_required(CellCreate.as_view()), name='cell-create'),

    url(r'^ion_channel_model/(?P<ionChannelId>[0-9]+)*$', IonChannelModelList.as_view(), name='ion-channel-model-index'),
    url(r'^ion_channel_model/create$', login_required(IonChannelModelCreate.as_view()), name='ion-channel-model-create'),
    url(r'^ion_channel_model/update/(?P<pk>[0-9]+)$', login_required(IonChannelModelUpdate.as_view()), name='ion-channel-model-update'),
    url(r'^ion_channel_model/delete/(?P<pk>[0-9]+)$', login_required(IonChannelModelDelete.as_view()), name='ion-channel-model-delete'),

    url(r'^patch_clamp/(?P<ionChannelId>[0-9]+)*$', PatchClampList.as_view(), name='patch-clamp-index'),
    url(r'^patch_clamp/create/(?P<ionChannelId>[0-9]+)*$', login_required(PatchClampCreate.as_view()), name='patch-clamp-create'),
    url(r'^patch_clamp/update/(?P<pk>[0-9]+)$', login_required(PatchClampUpdate.as_view()), name='patch-clamp-update'),
    url(r'^patch_clamp/delete/(?P<pk>[0-9]+)$', login_required(PatchClampDelete.as_view()), name='patch-clamp-delete'),
    url(r'^patch_clamp/detail/(?P<pk>[0-9]+)$', PatchClampDetail.as_view(), name='patch-clamp-detail'),

    url(r'^graph/(?P<ionChannelId>[0-9]+)*$', GraphList.as_view(), name='graph-index'),
    url(r'^graph/create/(?P<ionChannelId>[0-9]+)*$', login_required(GraphCreate.as_view()), name='graph-create'),
    url(r'^graph/update/(?P<pk>[0-9]+)$', login_required(GraphUpdate.as_view()), name='graph-update'),
    url(r'^graph/plot/(?P<pk>[0-9]+)$', login_required(save_digitized_plot), name='graph-plot'),
    url(r'^graph/delete/(?P<pk>[0-9]+)$', login_required(GraphDelete.as_view()), name='graph-delete'),

    url(r'^graph_data/(?P<graph_id>[0-9]+)$', GraphDataList.as_view(), name='graph-data-index'),
    url(r'^graph_data/create$', login_required(save_graph_data), name='graph-data-create'),
    url(r'^graph_data/delete/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataDelete.as_view()), name='graph-data-delete'),
    url(r'^graph_data/update/(?P<graph_id>[0-9]+)/(?P<pk>[0-9]+)/$', login_required(GraphDataUpdate.as_view()), name='graph-data-update'),

]

web_app/urls.py
"""
chopen URL Configuration
"""
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
import sys
# from ion_channel.views import index
from .views import index

# TODO: Check for conflicts in two accounts url pattern
# login_required() from 'django.contrib.auth.urls' redirects to accounts/login/ by default!

urlpatterns = [
    # url(r'^cms/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^pages/', include(wagtail_urls)),
    # url(r'^accounts/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include(('account.urls', 'account'), namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^digitizer/', include(('digitizer.urls', 'digitizer'), namespace="digitizer"), ),
    url(r'^ion_channel/', include(('ion_channel.urls', 'ion_channel'), namespace="ion_channel"), ),
    url(r'^api/', include(('api.urls', 'api'), namespace="api"), ),
    url(r'^index$', index ),
    url(r'^$', index ,name='home'),
    # url(r'^$', include(('homepage.urls', 'homepage'), namespace='homepage')),
    # url(r'^explorer/', include('explorer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ion_channel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


Cell_Type_CHOICES = (
    ('Xenopus Oocytes', 'Xenopus Oocytes'),
    ('Caenorhabditis elegans body wall muscle', 'Caenorhabditis elegans body wall muscle'),
    ('HEK', 'HEK'),
    ('CHO', 'CHO'),
    ('COS-7', 'COS-7'),
    ('Generic', 'Generic'),
)


class Cell(models.Model):
    cell_type = models.CharField(max_length=300,choices=Cell_Type_CHOICES,default='Xenopus Oocytes')
    membrane_capacitance = models.FloatField(default=2e-7, max_length=200,blank=True, null=True,verbose_name='Capacitance of the membrane (F)')
    specific_capacitance = models.FloatField(default=0.01,blank=True, null=True,verbose_name='Specific capacitance of the membrane (F/m2)')
    area = models.FloatField(default=2e-5, blank=True, null=True,verbose_name='Total area of the cell (m2)')

    def __unicode__(self):
        return self.cell_type

Method_CHOICES = (
    ('TMVC', 'Two Microelectrode Voltage Clamp'),
    ('Inside-Out', 'Inside-Out Patch Clamp'),
)

# TODO: Consider measurement fields: https://pypi.python.org/pypi/django-measurement


class PatchClamp(models.Model):
    cell = models.ForeignKey(Cell, default=1, on_delete=models.CASCADE)
    method = models.CharField(max_length=200,choices=Method_CHOICES,default='TMVC')
    duration = models.FloatField(verbose_name='Patch-Clamp Duration (ms)')
    start_time = models.FloatField(default=0,verbose_name='Start time (ms)')
    end_time = models.FloatField(verbose_name='End time (ms) (default=duration)')
    holding_potential = models.FloatField(verbose_name='Holding potential (mV)')
    voltage_start = models.FloatField(verbose_name='Initial voltage (mV)')
    voltage_end = models.FloatField(verbose_name='Final voltage (mV)')
    voltage_steps = models.FloatField(verbose_name='Voltage steps (mV)', default=10)
    depolarization_step = models.FloatField(blank=True, null=True, verbose_name='Depolarization step (mV)')
    cell_age = models.FloatField(default=None, blank=True, null=True,verbose_name='Age of the cell (days)')
    temperature = models.FloatField(default=21, blank=True, null=True,verbose_name='Temperature (Celsius)')
    Ca_concentration = models.FloatField(default=None, blank=True, null=True,verbose_name='Initial molar concentration of Calcium (uM)')
    # Cl_concentration = models.FloatField(default=None, blank=True, null=True,verbose_name='Initial molar concentration of Chloride (mM)')
    blockers = models.CharField(max_length=300, blank=True, null=True, verbose_name='Ion channel blockers (e.g. 500e-6 Cd2+,...)')
    extra_solution = models.TextField(blank=True, null=True, verbose_name='Extracellular Solution (e.g. 140e-3 NaCl, 5e-3 KCl,...)')
    pipette_solution = models.TextField(blank=True, null=True, verbose_name='Pipette Solution (e.g. 120e-3 KCl, 20e-3 KOH,...)')

    def __unicode__(self):
        return repr(self.cell) + ", " + str(self.method) + ", " + str(self.temperature) + " (C), " + "Holding Potential: " + \
               str(self.holding_potential) + " (mV), From: " + str(self.voltage_start) + ", To: " + str(self.voltage_end) + \
               ", Duration: "+str(self.duration) + " (ms), From: " + str(self.start_time) + ", To: " + str(self.end_time) + \
               ", [Ca]: " + str(self.Ca_concentration) + " (mM)"


Reference_Type_CHOICES = (
    ('Genomics', 'Genomics'),
    ('Proteomics', 'Proteomics'),
    ('Electrophysiology', 'Electrophysiology'),
    ('Combination', 'Combination')
)


class Reference(models.Model):
    doi = models.CharField(max_length=300, unique=True, blank=True, null=True)
    PMID = models.CharField(max_length=300, unique=True, blank=True, null=True)
    title = models.TextField(blank=True, null=True)
    citation = models.TextField(blank=True, null=True)
    year = models.CharField(max_length=300,blank=True, null=True)
    authors = models.CharField(max_length=300,blank=True, null=True)
    journal = models.CharField(max_length=300,blank=True, null=True)
    volume = models.CharField(max_length=300,blank=True, null=True)
    issue = models.CharField(max_length=300,blank=True, null=True)
    pages = models.CharField(max_length=300,blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now=True)
    username = models.ForeignKey(User,verbose_name='Contributor', on_delete=models.CASCADE)
    tags = models.TextField(blank=True, null=True)
    subject = models.CharField(max_length=300,choices=Reference_Type_CHOICES,default='Electrophysiology')
    file_url = models.URLField(blank=True, null=True)

    def __unicode__(self):
        return self.PMID + ", " + self.citation + ", " + self.year

    def clean(self):
        if self.doi == '' and self.PMID == '':
            raise ValidationError(_('Enter either DOI or PMID.'))


Channel_Type_CHOICES = (
    ('Voltage-gated potassium channels', 'KV'),
    ('Calcium-activated potassium channels', 'KCa'),
    ('Inwardly rectifying potassium channels', 'Kir'),
    ('Two-P potassium channels', 'K2p'),
    ('Voltage-gated calcium channels', 'CaV'),
    ('Voltage-gated sodium channels', 'NaV'),
    ('Voltage-gated proton channels', 'HV'),
    ('Voltage-gated chloride channels', 'ClV'),
    ('Transient receptor potential cation channels', 'TRP'),
    ('Cation channels sperm associated', 'CATSPER'),
    ('Cyclic nucleotide gated channels', 'CNG'),
    ('Two pore segment channels', 'TPCN'),
    ('Unknown', 'Unknown'),
)
Ion_Type_CHOICES = (
    ('Ca2+', 'Calcium'),
    ('K+', 'Potassium'),
    ('Cl-', 'Chloride'),
    ('Na+', 'Sodium'),
    ('Cation', 'Cation')
)
ANIMAL_CHOICES = (
    ('Homo sapiens (Human)', 'Human'),
    ('Rattus norvegicus (Rat)', 'Rat'),
    ('Mus musculus (Mouse)', 'Mouse'),
    ('Oryctolagus cuniculus (rabbit)', 'Rabbit'),
    ('Canis lupus familiaris (Dog)', 'Dog'),
    ('Xenopus laevis (African clawed frog)', 'African clawed frog'),
    ('Drosophila melanogaster (Fruit fly)', 'Fruit fly'),
    ('Caenorhabditis elegans (C. elegans)', 'C. elegans'),
    ('Danio rerio (zebrafish)', 'Zebrafish'),
    ('Panulirus interruptus (California spiny lobster)', 'California spiny lobster'),
    ('Panulirus argus (Caribbean spiny lobster)', 'Caribbean spiny lobster'),
    ('Aplysia californica (California sea hare)', 'California sea hare'),
    ('Schistosoma mansoni (Blood fluke)', 'Blood fluke'),
    ('Polyorchis penicillatus (penicillate jellyfish)', 'Penicillate Jellyfish'),
    ('Mustela putorius furo (domestic ferret)', 'Domestic ferret'),
    ('Doryteuthis pealeii (Longfin inshore squid) (Loligo pealeii)', 'Loligo pealeii'),
    ('Aplysia sp. (Sea hare)', 'Sea hare'),
    ('Ictalurus punctatus (channel catfish)', 'Channel catfish' ),
    ('Polyorchis penicillatus (penicillate jellyfish)', 'Penicillate jellyfish'),
    ('Squalus acanthias (Spiny dogfish)', 'Spiny dogfish'),
    ('Nematostella vectensis (starlet sea anemone)', 'Starlet sea anemone'),
    ('Cavia porcellus (domestic guinea pig)', 'Domestic guinea pig'),
    ('Blattella germanica (German cockroach)', 'German cockroach'),
    ('Ciona intestinalis (vase tunicate)', 'Vase tunicate'),
    ('Arabidopsis thaliana (thale cress)', 'Arabidopsis thaliana (thale cress)'),
    ('Zea mays', 'Zea mays'),
    ('Others', 'Others'),
)
Current_Type_CHOICES = (
    ('A-type', 'IA'),
    ('Delayed rectifier', 'Id'),
    ('M-type', 'IM'),
    ('Inwardly-rectifying', 'Iir'),
    ('Inwardly-rectifying and A-type', 'IA-Iir'),
    ('Outwardly-rectifying', 'Io'),
    ('Proton Current', 'Ih'),
    ('Inwardly-rectifying Proton Current', 'Ih-Iir'),
    ('Calcium Current', 'ICa'),
    ('Calcium L-type Current', 'ICa-L'),
    ('Calcium P/Q-type Current', 'ICa-P/Q'),
    ('Calcium N-type Current', 'ICa-N'),
    ('Calcium R-type Current', 'ICa-R'),
    ('Sodium Current', 'INa'),
    ('S-type', 'IS'),
)


class IonChannel(models.Model):
    channel_name = models.CharField(max_length=300, unique=True)
    full_name = models.CharField(blank=True, null=True, max_length=300)
    gene_symbol = models.CharField(null=True, max_length=300)
    isoform = models.CharField(blank=True, null=True, max_length=20)
    animal = models.CharField(blank=True, null=True, max_length=200,choices=ANIMAL_CHOICES)
    channel_type = models.CharField(blank=True, null=True, max_length=300,choices=Channel_Type_CHOICES)
    class_symbol = models.CharField(blank=True, null=True, max_length=300)
    subfamily = models.CharField(blank=True, null=True, max_length=20)
    member = models.CharField(blank=True, null=True, max_length=20)
    current_type = models.CharField(blank=True, null=True, max_length=300)
    aliases = models.CharField(blank=True, null=True, max_length=300)
    ion_type = models.CharField(blank=True, null=True, max_length=200,choices=Ion_Type_CHOICES)
    uniprot_id = models.CharField(blank=True, null=True, max_length=300)
    refSeq_id = models.CharField(blank=True, null=True, max_length=300)
    gene_id = models.CharField(blank=True, null=True, max_length=300)
    conductance = models.FloatField(default=10, blank=True, null=True, verbose_name='Single Channel Conductance (ps)')
    sequence = models.TextField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    create_date = models.DateTimeField()
    last_update = models.DateTimeField(auto_now=True)
    username = models.ForeignKey(User,verbose_name='Curator', on_delete=models.CASCADE)
    references = models.ManyToManyField(Reference, blank=True)
    links = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.channel_name


Axis_Type_CHOICES = (
    ('I', 'Current'),
    ('T', 'Time'),
    ('Tau_a', 'Activation Time'),
    ('Tau_i', 'Inactivation Time'),
    ('I_ss', 'Steady-state Current'),
    ('I_peak', 'Peak Current'),
    ('I_norm', 'Normalized Current'),

ion_channel/templates/ion_channel/graph_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Figures' %}{% endblock %}
{% block page_header %}{% trans 'Figures' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Figures' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-bar-chart"></i>

                    <h3 class="box-title">{% trans 'Figures' %}</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:graph-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Graph' %}
                        </a>
                    </div>
                </div>
                <div class="box-body table-responsive">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">{% trans 'ID' %}</th>
                            <th>{% trans 'Ion channel' %}</th>
                            <th>{% trans 'Patch Clamp' %}</th>
                            <th>{% trans 'Reference' %}</th>
                            <th>{% trans 'Ref Address' %}</th>
                            <th>{% trans 'Ref Caption' %}</th>
                            <th>{% trans 'Axis' %}</th>
                            <th>{% trans 'Figure' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for graph in graphs %}
                            <tr>
                                <td>{{ graph.id }}</td>
                                <td>{{ graph.ion_channel }}</td>
                                <td>
                                    <abbr title="{{ graph.patch_clamp }}">{{ graph.patch_clamp|truncatechars:100 }}</abbr>
                                </td>
                                <td>
                                    <a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ graph.reference.PMID }}">
                                        <abbr title="{{ graph.reference }}">{{ graph.reference|truncatechars:100 }}</abbr>
                                    </a>
                                </td>
                                <td>{{ graph.figure_ref_address }}</td>
                                <td>
                                    <abbr title="{{ graph.figure_ref_caption }}">{{ graph.figure_ref_caption|truncatechars:100 }}</abbr>
                                </td>
                                <td>
                                    {{ graph.y_axis_type }}{% trans '(' %}{{ graph.y_axis_unit }}{% trans ')' %}{% trans '-' %}{{ graph.x_axis_type }}{% trans '(' %}{{ graph.x_axis_unit }}{% trans ')' %}
                                </td>
                                <td>
                                    <a href="{{ graph.file.url }}">
                                        <img src="{{ graph.file.url }}" style="max-width:100%; max-height:100%;" />
                                    </a>
                                {% if graph.digitized_plot %}
                                    <a href="{{ graph.digitized_plot.url }}">
                                        <img src="{{ graph.digitized_plot.url }}" style="max-width:100%; max-height:100%;" />
                                    </a>
                                {% endif %}
                                {% if graph.digitized_plot_file %}
                                    <a href="{{ graph.digitized_plot_file.url }}">{% trans 'Download pickle' %}</a>
                                {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'ion_channel:graph-update' graph.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:graph-delete' graph.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                    <a href="{% url 'digitizer:digitize' graph.id %}"
                                       class="badge bg-green">
                                        <i class="fa fa-file-text-o"></i>
                                        {% trans 'Digitize' %}
                                    </a>
                                    <a href="{% url 'ion_channel:graph-plot' graph.id %}"
                                       class="badge bg-blue">
                                        <i class="fa fa-area-chart"></i>
                                        {% trans 'Plot' %}
                                    </a>
                                    <a href="{% url 'ion_channel:graph-data-index' graph.id %}"
                                       class="badge bg-yellow">
                                        <i class="fa fa-file-text-o"></i>
                                        {% trans 'Series' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}

ion_channel/templates/ion_channel/index.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}{% trans 'Home' %}{% endblock %}
{% block page_header %}{% trans 'Home' %}{% endblock %}
{% block breadcrumb %}

{% endblock %}

{% block content %}

{% endblock %}

ion_channel/templates/ion_channel/patchclamp_list.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_filters %}

{% block page_title %}{% trans 'Patch Clamps' %}{% endblock %}
{% block page_header %}{% trans 'Patch Clamps' %}{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url 'ion_channel:home' %}"><i class="fa fa-home"></i> {% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Patch Clamps' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-pinterest-p"></i>
                    <h3 class="box-title">{% trans 'Patch Clamp' %}</h3>
                    <div class="box-tools pull-right">
                        <a href="{% url 'ion_channel:patch-clamp-create' %}"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            {% trans 'Add Patch Clamp' %}
                        </a>
                    </div>
                </div>
                <div class="box-body table-responsive">
                    <table id="result_table" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">ID</th>
                            <th>{% trans 'Cell' %}</th>
                            <th>{% trans 'Patch clamp method' %}</th>
                            <th>{% trans 'Duration (ms)' %}</th>
                            <th>{% trans 'Holding potential (mV)' %}</th>
                            <th>{% trans 'From (mV)' %}</th>
                            <th>{% trans 'To (mV)' %}</th>
                            <th>{% trans 'Steps (mV)' %}</th>
                            <th>{% trans 'Temperature (Celsius)' %}</th>
                            <th>{% trans '[Ca2+] (mM)' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for patch_clamp in patch_clamps %}
                            <tr>
                                <td>{{ patch_clamp.id }}</td>
                                <td>{{ patch_clamp.cell }}</td>
                                <td>{{ patch_clamp.method }}</td>
                                <td>{{ patch_clamp.duration }}</td>
                                <td>{{ patch_clamp.holding_potential }}</td>
                                <td>{{ patch_clamp.voltage_start }}</td>
                                <td>{{ patch_clamp.voltage_end }}</td>
                                <td>{{ patch_clamp.voltage_steps }}</td>
                                <td>{{ patch_clamp.temperature }}</td>
                                <td>{{ patch_clamp.Ca_concentration }}</td>
                                <td>
                                    <a href="{% url 'ion_channel:patch-clamp-detail' patch_clamp.id %}"
                                       class="badge bg-yellow">
                                        <i class="fa fa-eye"></i>
                                        {% trans 'View Detail' %}
                                    </a>
                                    <a href="{% url 'ion_channel:patch-clamp-update' patch_clamp.id %}"
                                       class="badge bg-light-blue">
                                        <i class="fa fa-edit"></i>
                                        {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'ion_channel:patch-clamp-delete' patch_clamp.id %}"
                                       class="badge bg-red">
                                        <i class="fa fa-remove"></i>
                                        {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block inline-script %}
    <script type="text/javascript">
        $("#result_table").dataTable();
    </script>
{% endblock %}